training:
  data_path: "../datasets/nyuv2"
  pretrained_model_path: "../models/depth_anything_v2_metric_hypersim_vitl.pth"
  divisible_by: 14
  backbone: "vitl"

  batch_size: 2
  epochs: 50

  freeze_backbone_until: -1

  optimizer:
    type: "adam"
    lr: 1e-3
    weight_decay: 1e-7

  lr_scheduler:
    type: "plateau"
    mode: "min"
    factor: 0.1
    patience: 2

  output_dir: "./checkpoints-dpt"
  save_intermediate_models: True
  device: "cuda"
  debug: true
  # Use a standard 640x480 resolution
  input_width: 640
  input_height: 480

logging:
  level: "DEBUG"

profiling:
  enable: false
  steps_to_profile: 5
  export_trace: "./profile_trace.json"
