training:
  data_path: "../datasets/nyuv2"
  pretrained_model_path: ""
  backbone: "vitl"

  batch_size: 1 # > 1 unsupported by mps
  epochs: 20
  freeze_backbone_until: 5

  optimizer:
    type: "adam"
    lr: 1e-4
    weight_decay: 1e-7

  lr_scheduler:
    type: "plateau"
    mode: "min"
    factor: 0.1
    patience: 2

  output_dir: "./checkpoints_dpt"
  save_intermediate_models: False
  device: "cuda"
  debug: true
  # Use a standard 640x480 resolution
  input_width: 640
  input_height: 480

logging:
  level: "DEBUG"

profiling:
  enable: false
  steps_to_profile: 5
  export_trace: "./profile_trace.json"
